nyc_taxi:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5433') | int }}"
      dbname: nyctaxi
      user: nyctaxi
      password: nyctaxi
      schema: staging
      threads: 4
